baseURL = "https://tehilimsefardi.com/"
languageCode = "es"
title = "Tehilim Sefardí"

[params]
  description = "Libro de Salmos en hebreo con traducción al español y transliteración sefardí"
  author = "Tehilim Sefardí"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
