baseURL = "https://tehilimsefardi.com/"
languageCode = "es"
title = "Tehilim Sefardí"
theme = "minithilim"
enableRedirects = true

[params]
  description = "Los Salmos de David en hebreo con traducción al español y transliteración sefaradí. Nusaj Sefard."
  author = "Shlomo Peretz"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "JSON"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
