#!/usr/bin/env python3
"""Write title_en to all 150 tehilim JSON files (titles derived from title_es)."""

import json, os

BASE = os.path.join(os.path.dirname(__file__), '..', 'data', 'tehilim')

TITLES_EN = {
    1:   "Blessed Is the Man",
    2:   "Why Do the Nations Rage?",
    3:   "A Psalm of David When He Fled",
    4:   "Trust in God at Eventide",
    5:   "Morning Prayer of Trust",
    6:   "Prayer in Time of Affliction",
    7:   "Prayer Seeking Divine Justice",
    8:   "God's Glory and Man's Dignity",
    9:   "Praise for Divine Justice",
    10:  "Cry Against the Arrogance of the Wicked",
    11:  "Trust in the Eternal Amid Danger",
    12:  "Cry Against Falsehood; Divine Promise",
    13:  "Prayer in Anguish; Trust in Salvation",
    14:  "Universal Corruption; Hope in the Eternal",
    15:  "The Righteous Who Dwell on God's Holy Mountain",
    16:  "Joyful Trust in the Eternal",
    17:  "Prayer of the Innocent Seeking Protection",
    18:  "David's Song of Victory",
    19:  "God's Glory in Creation and in the Torah",
    20:  "Prayer for the King's Victory",
    21:  "Thanksgiving for the King's Victory",
    22:  "Cry of Anguish and Praise to God",
    23:  "The Eternal Is My Shepherd",
    24:  "The King of Glory Enters Zion",
    25:  "Prayer of Trust and Petition for Guidance",
    26:  "Prayer of the Righteous Who Trust in God",
    27:  "The Eternal Is My Light and My Salvation",
    28:  "Cry for Help and Thanksgiving",
    29:  "The Voice of the Eternal Over the Waters",
    30:  "Praise for Divine Deliverance",
    31:  "Trust in God Amid Affliction",
    32:  "Blessed Is the One Whose Sin Is Forgiven",
    33:  "Praise to the Creator and Sovereign",
    34:  "Praise for Deliverance and the Fear of God",
    35:  "Prayer Seeking Justice Against Enemies",
    36:  "The Wickedness of the Wicked and the Goodness of God",
    37:  "The Destiny of the Righteous and the Wicked",
    38:  "Prayer of the Afflicted Penitent",
    39:  "Human Frailty Before God",
    40:  "Thanksgiving and Plea for Help",
    41:  "Blessed Is the Merciful; Prayer of the Sick",
    42:  "The Soul's Longing for God",
    43:  "Prayer Seeking Justice and Divine Light",
    44:  "National Lament and Plea for Help",
    45:  "The King's Wedding Song",
    46:  "God Is Our Refuge and Strength",
    47:  "God, Great King Over All the Earth",
    48:  "Zion, City of the Great King",
    49:  "The Vanity of Wealth and Hope in God",
    50:  "The True Worship God Requires",
    51:  "Prayer of Repentance and Forgiveness",
    52:  "The Destiny of the Wicked and the Righteous",
    53:  "Universal Corruption and the Hope of Salvation",
    54:  "Cry for Help and Trust in God",
    55:  "Cry Against the Betrayal of a Friend",
    56:  "Trust in God Amid Danger",
    57:  "Praise and Trust in God Amid Danger",
    58:  "Against Unjust Judges",
    59:  "Deliverance from Enemies",
    60:  "National Lament and Trust in God",
    61:  "Refuge in God from the Ends of the Earth",
    62:  "The Soul at Rest in God Alone",
    63:  "The Soul Thirsting for God",
    64:  "Divine Protection Against Conspirators",
    65:  "Praise to God for His Blessings",
    66:  "Praise to God for His Wondrous Works",
    67:  "May All Nations Praise God",
    68:  "The Victorious God Who Leads His People",
    69:  "Cry from the Depths and Hope in God",
    70:  "Urgent Cry for Help",
    71:  "Prayer of an Elder Who Trusts in God",
    72:  "Prayer for the Just King and His Universal Reign",
    73:  "The Wicked's Prosperity Resolved in the Sanctuary",
    74:  "Lament for the Destruction of the Sanctuary",
    75:  "God the Just Judge Who Humbles the Proud",
    76:  "God Victorious in Zion",
    77:  "Comfort in Affliction Remembering God's Works",
    78:  "God's Works in the History of Israel",
    79:  "Lament for the Desecration of Jerusalem",
    80:  "Plea for the Restoration of Israel",
    81:  "Call to Faithfulness at the Solemn Feast",
    82:  "God Judges the Unjust Judges",
    83:  "Prayer Against the Coalition of Israel's Enemies",
    84:  "Longing for the House of God",
    85:  "Prayer for Restoration and Peace",
    86:  "David's Prayer in Affliction",
    87:  "Zion, Mother of the Peoples",
    88:  "Cry of a Soul on the Edge of Death",
    89:  "The Eternal Mercies and the Davidic Covenant",
    90:  "The Eternity of God and the Brevity of Man",
    91:  "He Who Dwells in the Shelter of the Most High",
    92:  "A Song for the Sabbath Day",
    93:  "The Eternal Reigns in Majesty",
    94:  "God, Judge of the Earth, Punishes Oppressors",
    95:  "Call to Praise and Obedience",
    96:  "Sing to the Eternal a New Song",
    97:  "The Eternal Reigns with Justice Over All the Earth",
    98:  "A New Song for the Wonders of the Eternal",
    99:  "The Holy Eternal Reigns Over the Nations",
    100: "Acclaim the Eternal, All the Earth",
    101: "A Promise to Live with Integrity",
    102: "Prayer of the Afflicted Who Cries to the Eternal",
    103: "Bless the Eternal, O My Soul, for His Kindnesses",
    104: "Hymn to God, Creator and Sustainer of the Universe",
    105: "God's Wonders with Israel from Abraham to the Promised Land",
    106: "Confession of Israel's Sins Throughout History",
    107: "Thanksgiving for the Redemption of the Eternal",
    108: "Trust in God for Victory Over Enemies",
    109: "Cry Against Accusers and Trust in Divine Salvation",
    110: "The Messianic Priest-King After the Order of Melchizedek",
    111: "Praise to God for His Wondrous Works and His Covenant",
    112: "Blessed Is the Man Who Fears the Eternal",
    113: "Praise the Eternal Who Exalts the Humble",
    114: "The Eternal Shakes the Earth When Israel Left Egypt",
    115: "Glory to God Alone, Not to Idols",
    116: "Thanksgiving for Deliverance from Death",
    117: "Praise the Eternal, All Nations",
    118: "Thanksgiving for the Salvation of the Eternal",
    119: "Meditation on the Torah of God — Alphabetic Acrostic",
    120: "Cry for Deliverance from Lying Lips",
    121: "The Eternal Is Your Guardian",
    122: "Prayer for the Peace of Jerusalem",
    123: "Prayer of the Humbled Who Wait on the Eternal",
    124: "The Eternal Was on Our Side",
    125: "The Eternal Surrounds His People as Mountains Surround Jerusalem",
    126: "The Eternal Restored the Fortunes of Zion",
    127: "Unless the Eternal Builds the House, Its Builders Labor in Vain",
    128: "Blessed Is the One Who Fears the Eternal",
    129: "Israel Persecuted but Not Defeated",
    130: "Out of the Depths I Call to You",
    131: "Humility and Trust in the Eternal",
    132: "The Eternal Chose Zion and the Davidic Dynasty",
    133: "How Good and Pleasant Is the Unity of Brothers",
    134: "Evening Blessing in the House of the Eternal",
    135: "Hallelujah for the Wonders of the Eternal with Israel",
    136: "The Eternal's Steadfast Love Endures Forever — the Great Hallel",
    137: "By the Rivers of Babylon",
    138: "Praise for the Eternal's Steadfast Love and Faithfulness",
    139: "The Eternal Knows All and Is Everywhere",
    140: "Deliver Me from the Violent Man",
    141: "Prayer to Guard Against the Wicked",
    142: "Cry in the Cave — Only the Eternal Is My Refuge",
    143: "Prayer in Anguish — Teach Me Your Way",
    144: "David's Prayer Before Battle",
    145: "Great Praise — David's Acrostic",
    146: "Praise the Eternal, Defender of the Humble",
    147: "Hallelujah for the Power and Goodness of the Eternal",
    148: "Hallelujah — Let All Creation Praise the Eternal",
    149: "A New Song — Victory and Glory of the Faithful",
    150: "Final Hallelujah — Let All That Breathes Praise the Eternal",
}

def main():
    updated = 0
    for i in range(1, 151):
        key = f"{i:03d}"
        path = os.path.join(BASE, f"{key}.json")
        with open(path, encoding='utf-8') as f:
            data = json.load(f)
        data['title_en'] = TITLES_EN[i]
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        updated += 1
        print(f"  {key}: {TITLES_EN[i]}")
    print(f"\nDone. Updated {updated} files.")

if __name__ == '__main__':
    main()
